name: Daily Shanghai Disneyland Price Tracker

on:
  schedule:
    # GitHub Actions uses UTC. 22:00 UTC ≈ 08:00 AEST (non-DST).
    # You can add another time for AEDT if you like.
    - cron: '0 22 * * *'
  workflow_dispatch:

jobs:
  run-tracker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraper
        run: |
          python klook_price_tracker.py

      - name: Commit & push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          if ! git diff --cached --quiet; then
            git commit -m "chore: update prices [skip ci]"
            git push
          else
            echo "No changes to commit."
          fi
