name: Daily Shanghai Disneyland Price Tracker

permissions:
  contents: write

on:
  schedule:
    # Run at 8:00 AM Melbourne time (22:00 UTC previous day)
    - cron: '0 22 * * *'
    # Run at 8:00 PM Melbourne time (10:00 UTC same day)
    - cron: '0 10 * * *'
  workflow_dispatch:

jobs:
  run-tracker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - run: python klook_price_tracker.py

      - name: Commit & push CSV
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update prices [skip ci]"
          file_pattern: data/shanghai_disneyland_prices.csv
